spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: none
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
