trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  displayName: build
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: CopyFiles@2
  displayName: Copy Files to artifact staging directory
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/build/libs/app-metlife-team10-0.0.1-SNAPSHOT.jar'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'metlife-it-hackathon(c78a7e0d-77b8-4816-b9f7-ac6d97d997be)'
    appType: 'webAppLinux'
    WebAppName: 'app-metlife-team10'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/build/libs/app-metlife-team10-0.0.1-SNAPSHOT.jar'
